apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-operator
    release: mysql-operator
  name: data-mysql-operator-0
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
