apiVersion: v1
kind: Pod
metadata:
  name: lts-pod
spec:
 containers:
    - name: litespeed
      image: 23251826/wp-lts:k8s
      imagePullPolicy: Always
      env:
        - name: MYSQL_DATABASE
          value: "database1"
        - name: MYSQL_USER
          value: "wp_user1"
        - name: MYSQL_PASSWORD
          value: "cGFzc3dvcmQxCg=="
        - name: MYSQL_HOST
          value: "my-cluster-mysql"
