---

- name: Fetch last stable kubectl ver
  shell: curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt | cat -
  register: kubectl_ver
  

- name: Download kubectl archive
  get_url:
    url: "{{ kubectl_url }}"
    dest: "{{ bin_dir }}/kubectll"
    mode: 0755

- name: Check if kubectl works properly
  shell: kubectll get nodes
  ignore_errors: yes
  register: kubectlrc
  failed_when: kubectlrc.rc != 0
