---
- name: download helm tgz to local
  get_url:
    url: "{{ helm_url }}"
    dest: /tmp/{{ helm_url | basename }}

- name: unarchive helm
  unarchive: 
    src: "{{ helm_url }}"
    dest: /tmp
    copy: no

- name: create the installation directory
  file:
    path: "{{ bin_dir }}"
    state: directory

- name: copy helm binary
  copy:
    src: /tmp/linux-amd64/helm
    dest: "{{ bin_dir }}/helm"
    mode: 0755
    remote_src: yes

- include_tasks: kubectl.yaml 

